Repository CascadeBot/CascadeBot, pull requests merged in 2019-06, with the labels that each got.

#112 Settings annotation
  src/main/java/org/cascadebot/cascadebot/commandmeta/CommandContext.java
  src/main/java/org/cascadebot/cascadebot/commands/core/PrefixCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/ModuleDisableSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/ModuleEnableSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/ModuleListSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/SettingsCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagCategorySubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagCreateSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagDeleteSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagEditSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagListSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/TagRawSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/music/PauseCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/music/ResumeCommand.java
  src/main/java/org/cascadebot/cascadebot/data/objects/GuildData.java
  src/main/java/org/cascadebot/cascadebot/data/objects/GuildPermissions.java
  src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettings.java
  src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettingsCore.java
  src/main/java/org/cascadebot/cascadebot/data/objects/Setting.java
  src/main/java/org/cascadebot/cascadebot/data/objects/SettingsContainer.java
  src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
Labels: type: core functionality

#133 Update example config and wildcard checking
  config.example.yml
  src/main/java/org/cascadebot/cascadebot/permissions/PermissionsManager.java
Labels: type: core functionality

#121 Update README.md
  README.md
Labels: type: meta

#135 Use the abstract discord URL
  README.md
  src/main/java/org/cascadebot/cascadebot/Constants.java
Labels: type: meta

#134 Contributing guidelines
  .github/CONTRIBUTING.md
Labels: type: meta

#123 Feature/permissions command
  src/main/java/org/cascadebot/cascadebot/UnicodeConstants.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionAddSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionCreateSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionInfoSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionLinkRoleSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionListSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionMoveSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionRemoveSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionSwitchSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionUnlinkRoleSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionAddSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionGroupSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionListSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionRemoveSubCommand.java
  src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionTestSubCommand.java
  src/main/java/org/cascadebot/cascadebot/data/objects/GuildPermissions.java
  src/main/java/org/cascadebot/cascadebot/messaging/Messaging.java
  src/main/java/org/cascadebot/cascadebot/utils/PermissionCommandUtils.java
Labels: module: management, status: pr in progress, type: core functionality

#136 Fix: Tags ran when commands also ran
  src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
Labels: type: bug

#137 Everything needs a default constructor :P
  src/main/java/org/cascadebot/cascadebot/data/database/DatabaseManager.java
  src/main/java/org/cascadebot/cascadebot/permissions/objects/Group.java
Labels: type: bug

#138 Fix queue hanging forever when a song playing but nothing in the queue
  src/main/java/org/cascadebot/cascadebot/commands/music/QueueCommand.java
Labels: type: bug
